### ISSUE TITLE
two classes EAGLESource ?

### ISSUE THREAD

**Issue by teuben** [kyleaoman/martini#2]
I could not reproduce the martini_eagle notebook, but then continued with the python converted one. The first error is:
    TypeError: __init__() got an unexpected keyword argument 'db_user'
so I comment this out, and then get another error from which it appears as if there is a 2nd EAGLESource class, now appearing in the installed sources.py which seems to use local files.The parent sources.py in the github repo is very different. I guess this is some python trick that newbies like me are not used to, but this is then very confusing. Is that related to the optional pip installs mentioned inthe installation notes?

**Comment by kyleaoman** [comment]
Could you clarify whether you were unable to follow the notebook after following the installation instructions from within the notebook? It sounds like you were trying to use an older version of the EAGLESource module, but the installation instructions in the notebook should get the latest version.

If you install from pypi (e.g. 'pip install astromartini'), then the last version uploaded to pypi will be installed. Right now, the pypi version hasn't been updated since some major changes to the EAGLESource module. The old version will only work with internal (private) access to the EAGLE data. The new version is designed to actually work with the public data.

**Comment by teuben** [comment]
I guess with the latest update, and the pip method of installing, all my troubles are gone.
