### ISSUE TITLE
How does the tangential velocity of neutral hydrogens affect the results of the Martini calculation?

### ISSUE THREAD

**Issue by z20230220** [kyleaoman/martini#70]
**Problem Description**
The “line of sight” is along the ‘x’ axis. I only change the vy and vz of neutral hydrogens optionally to test whether these components can affect  the results of the Martini calculation. In the end, I find that this change does make a difference to the final results. 

But with my current knowledge, the tangential velocity(vy and vz) won't affect the result. Is there any physical mechanism by which the tangential velocity of neutral hydrogen can affect the final observation?

I will display the relative error as follow. The values in the figure represent the following meanings:
$$relative \ Delta \ mom\textbf{i}=\left|{\frac{mom\textbf{i}-mom_{test}\textbf{i}}{mom\textbf{i}}}\right|$$
The value without subscript "test" means the result without change of vy and vz, vice versa.

**Comment by z20230220** [comment]
![@P{K75Y}V2IP`GQ A0Y439Q](https://github.com/kyleaoman/martini/assets/125883770/8e2ffe7b-677c-403f-999f-5e4fbd9d5d53)
![X{$Q4J(ZE5P@PP D%`RB_`1](https://github.com/kyleaoman/martini/assets/125883770/1e2ea325-de27-44a4-b572-2bbff426bdb3)
![N_14T1T2F{MY`@ZL%ZNA{ O](https://github.com/kyleaoman/martini/assets/125883770/02b9ba3f-6a09-48be-99ce-de40e8db616a)

**Comment by kyleaoman** [comment]
Hi, thanks for the question. The v_y and v_z components do contribute because while the line of sight is along the x-axis (i.e. the centre of the source is placed at the specified distance along the x-axis), the line of sight velocities used to calculate the spectra of the particles are calculated in a spherical projection (see https://martini.readthedocs.io/en/latest/sources/index.html#particle-arrays). This difference is more or less negligible for sources that subtend a small angle on the sky, but for a mock observation of something like M31 or the LMC it would start to matter more.

My expectation is therefore that the differences that you're seeing in mom0 are due to particles close to the edge of the cube in the spectral direction shifting flux into or out of the bandpass. In mom1 and mom2 you can see a background trend for larger differences further from the centre of the cube. (I'm assuming here that the source and cube share the same centre, otherwise differences should be minimized at the source centre.)

My best guess to explain the larger but more localized differences, especially in mom1 (the sort of black wiggly filament) is that there are some particles contributing to the edge channels with velocities far from the typical velocity in the pixel, such that if they shift in or out of the bandpass mom1 is most strongly affected.

It's difficult to say more without knowing the absolute scales we're dealing with - the angular size of the cube, absolute (not differenced) moment maps, and how much you're changing the y and z velocities.

The other thing that could contribute, but seems less likely based on what I'm seeing, is precision limitations of floats. Calculating the radial velocity (in spherical coordinates) from the Cartesian components involves all of the position and velocity components. If you make the y and z velocities large enough you could cause significant floating point rounding errors even for particles directly along the line of sight. I have a harder time reconciling that interpretation with your figures, though.

To check that my explanation makes sense you could try the test again with more channels or wider channels such that no particles are near the edge of the bandpass. If I'm right that should reduce the differences in mom1 to the level of numerical noise, and the differences in mom1 and mom2 should be zero at the centre of the source and increasing away from it (I guess that you're applying a constant shift in v_y and v_z to all particles). I'd also suggest that looking at channel maps instead of or in addition to moment maps might help.

If your results remain difficult to interpret after that, I can try some tests with more controlled source particle distributions to see what's going on.

**Comment by z20230220** [comment]
Thank you for your patient answer! In yesterday's work, the shift in v_y and v_z of each particle varies by a random number of -1000km/s to 1000km/s. However, the typical velocity of particles is about 200km/s. 

In order to better analyze the impact of this shift on the result, I use the toy-galaxy data in demo and repeat the previous steps. 
The projection of toy-galaxy density in x-y plane and z-y plane are shown in the following figures:

<img src="https://github.com/kyleaoman/martini/assets/125883770/e6aad9e2-9e81-480f-bab9-658a3cda09d4" width="300" height="270" style="margin-right: 10px;">
<img src="https://github.com/kyleaoman/martini/assets/125883770/a2eaaee7-c846-42fd-a161-7c69beff4a3c" width="300" height="270">

Then I use Martini to calculate some relative quantities, the relative parameters are set as follow:

**distance=3Mpc, ra=0deg, dec=0deg, h=0.7
n_px_x=150, n_px_y=150, n_channels=100,
px_size=10.0 arcsec, channel_width=10.0 km/s, velocity_centre=source.vsys**

and plot mom0, mom1 and mom2 as follow:
![2H9K{Y@9KNQW2FLT F%{2@X](https://github.com/kyleaoman/martini/assets/125883770/bfebaf2d-c5e8-49f1-8d6e-17c135720f0b)
(It seems that this channels is wild enough to include all the particles.)

Then I apply a constant shift in v_y and v_z to all particles, i.e. $\delta v_{y}=\delta v_{z}=+30km/s $, and calculate a new FluxCube by same steps.
![{E%JHZK{$FR3V 3BU3J3FIX](https://github.com/kyleaoman/martini/assets/125883770/8dffec92-fa1f-4b58-9cec-9a72a58cc2d1)
(There is no obvious change.)

After that, I plot relative error of mom0, mom1 and mom2:

<img src="https://github.com/kyleaoman/martini/assets/125883770/6ef0b9f6-62e2-4df7-a778-341bade46313" width="230" height="220" style="margin-right: 10px;">
<img src="https://github.com/kyleaoman/martini/assets/125883770/b32e1fa8-39b9-4d18-8c34-3817ec8f3f84" width="230" height="220">
<img src="https://github.com/kyleaoman/martini/assets/125883770/5d7db7e7-c0b2-44cf-aa1f-34a4040d6fc0" width="230" height="220">

Just as you predicted, the error at the edge is greater than the error at the center due to vy,vz projection effect. (The source and cube share a same centre.)  What's more, through the middle figure, we can also find that the relative error is minimized in a 45 degree diagonal line. This phenomenon can be proved by simple solid geometry:

The vector of velocity change can be write as: 
$$\vec{V}_{add}=(0,30,30)$$
When the vector is perpendicular to the position vector of a particle, the result will least affected by the change in velocity. (The change of velocity has no effect on the radial velocity of the particle.)
Let's call the coordinates of the  is $\vec{r}=(x,y,z)$, it will satisfy the following equation:
$$\vec{r} \cdot \vec{V}_{add}=0$$
i.e. $$y=-z$$
That is the diagonal line in this figure. (Notice that the quantity in the ordinate is "-z".)

**Comment by z20230220** [comment]
There are many small circles in above figures, i guess they are contributed by MARTINI’s beam classes. But I still confuse that why the relative error are obvious at the edge of these circles?

<img src="https://github.com/kyleaoman/martini/assets/125883770/55d38a50-a094-4d58-94dc-aafe87d4cda0" width="300" height="300" style="margin-right: 10px;">

**Comment by z20230220** [comment]
In addition, I just have a little question. Does Martini's Hubble flow for particles take into account that particles at different distances from the observer have different recessional speeds? For example, particles that are closer to the observer have a smaller recessional velocity.

**Comment by kyleaoman** [comment]
Ok thanks for the additional tests. Based on those moment maps I think that we understand where the differences are coming from, and the code is behaving as it should.

Regarding the small differences around the edge of the mom0 map, these are so small that I think that they are most likely coming from the limited precision of floats. 1e-16 is about the smallest relative difference that can be tracked, e.g.

```
>>> 1-1e-14
0.99999999999999
>>> 1-1e-15
0.999999999999999
>>> 1-1e-16
0.9999999999999999
>>> 1-1e-17
1.0
```

and you're pretty close to that regime in the map. I don't think that there's much that can/should be done about this, especially since the commitment in MARTINI is that flux errors per particle of up to 1% are allowed. I also can't think of any science case using MARTINI that would be sensitive to relative errors at the 1e-14 level (but if you can I'd be curious to know, of course!).

About the recessional velocity, that's set as a single value for all particles in the source. It would make more sense to calculate it separately for each particle - it could start to matter quite a lot for large sources like galaxy clusters or mocks with a large extent in velocity in general. I'll open an issue to remind me to fix that. If you would like that change applied quickly let me know and I can prioritize it.

**Comment by z20230220** [comment]
Okay, thank you very much for the detailed explanation, I have gained a lot from it. I am very pleased to be able to use a program as efficient as MARTINI, and I am really looking forward to the correction of the recessional velocity being applied to MARTINI as soon as possible. Thank you again for your help!

**Comment by kyleaoman** [comment]
@z20230220 updated in v2.1.2 now on pypi, some explanation added in https://martini.readthedocs.io/en/latest/sources/index.html#distance-peculiar-velocity-right-ascension-and-declination. Thanks again for the very clear and diligently researched question, and if you have any further questions/issues don't hesitate to get in touch. I look forward to seeing what you do with the code! :)

One thing that I didn't include in this update is an option for the peculiar velocity to be in an arbitrary (vector) direction. If that's needed let me know (but you could also just apply a constant shift to the particle velocities yourself, e.g. with the source module's `boost` method).
